export { SiteHeader } from './SiteHeader'
export { HomeHero } from './HomeHero'
export { OlgishCakesFounder } from './OlgishCakesFounder'
export { Bestsellers } from './Bestsellers'
export { Markets } from './Markets'
export { Reviews } from './Reviews'
export { Occasions } from './Occasions'
export { HomeFaq, faqItems } from './HomeFaq'
export { Instagram } from './Instagram'
