create table if not exists public.contact_enquiries (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text,
  address text,
  city text,
  postcode text,
  cake_interest text,
  date_needed text,
  message text not null,
  note text,
  gift_note text,
  referrer text,
  attachment_names text[],
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.contact_enquiries enable row level security;

revoke all on table public.contact_enquiries
  from public, anon, authenticated;

grant all on table public.contact_enquiries
  to service_role;

grant usage, select on sequence public.contact_enquiries_id_seq
  to service_role;
