create table if not exists public.workshop_enquiries (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text,
  event_type text not null,
  group_size text not null,
  location text not null,
  preferred_date date not null,
  decoration_theme text,
  brief text not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.workshop_enquiries enable row level security;

revoke all on table public.workshop_enquiries
  from public, anon, authenticated;

grant all on table public.workshop_enquiries
  to service_role;

grant usage, select on sequence public.workshop_enquiries_id_seq
  to service_role;
