create table if not exists public.event_photo_link_clicks (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.event_photo_requests(id) on delete cascade,
  event_name text not null,
  link_key text not null,
  link_title text not null,
  link_href text not null,
  clicked_at timestamptz not null default timezone('utc'::text, now()),
  constraint event_photo_link_clicks_event_name_length check (
    char_length(trim(event_name)) between 1 and 120
  ),
  constraint event_photo_link_clicks_link_key_length check (
    char_length(trim(link_key)) between 1 and 80
  ),
  constraint event_photo_link_clicks_link_title_length check (
    char_length(trim(link_title)) between 1 and 120
  ),
  constraint event_photo_link_clicks_link_href_length check (
    char_length(trim(link_href)) between 1 and 500
  )
);

create index if not exists event_photo_link_clicks_clicked_at_idx
  on public.event_photo_link_clicks (clicked_at desc);

create index if not exists event_photo_link_clicks_event_name_idx
  on public.event_photo_link_clicks (event_name);

create index if not exists event_photo_link_clicks_request_id_idx
  on public.event_photo_link_clicks (request_id);

create index if not exists event_photo_link_clicks_link_key_idx
  on public.event_photo_link_clicks (link_key);

alter table public.event_photo_link_clicks enable row level security;

revoke all on table public.event_photo_link_clicks
  from public, anon, authenticated;

grant select, insert, update, delete on table public.event_photo_link_clicks
  to service_role;
